# Generated by Django 5.2.13 on 2026-04-08 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'draft'), ('public', 'public'), ('deleted', 'deleted')], default='draft', max_length=10),
        ),
    ]
