# Generated by Django 5.2.13 on 2026-04-10 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_get_post_functions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'draft'), ('public', 'public'), ('deleted', 'deleted')], default='draft', help_text='Select the publication status (draft, public or deleted).', max_length=10),
        ),
    ]
