# Generated by Django 5.2.13 on 2026-04-13 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_replace_add_post_procedure_with_function'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='total_comments',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='total_likes',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='total_shares',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
