# Generated by Django 5.2.13 on 2026-04-09 17:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0002_interaction_get_functions'),
        ('posts', '0006_get_post_functions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='share',
            constraint=models.UniqueConstraint(fields=('user', 'post'), name='unique_user_post_share'),
        ),
    ]
