# Generated by Django 5.2.13 on 2026-04-10 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0003_interaction_status_and_sp'),
        ('interaction', '0003_share_unique_user_post_share'),
    ]

    operations = [
    ]
