# Generated by Django 5.2.13 on 2026-04-13 17:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0005_user_interaction_history_functions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='shared_with',
            field=models.ManyToManyField(blank=True, related_name='received_shares', to=settings.AUTH_USER_MODEL),
        ),
    ]
