# Generated by Django 5.2.13 on 2026-04-10 16:58

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authx', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Mobile number must not start with 0 and must contain only digits.', regex='^[1-9]\\d*$')]),
        ),
        migrations.AddConstraint(
            model_name='userprofile',
            constraint=models.CheckConstraint(condition=models.Q(('mobile_number__regex', '^[1-9]\\d*$')), name='mobile_number_valid_format_and_no_leading_zero'),
        ),
    ]
